server:
  port: 8000
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: example@gmail.com
    password: example_password
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: email-notifications
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer